### ISSUE TITLE
Loady doesn't handle columns with newlines

### ISSUE THREAD

**Issue by scottjacobsen** [teeparham/loady#1]
Because loady reads lines using the `IO#each` function [here](https://github.com/teeparham/loady/blob/9fb8db71e43066dd6be8c7b429436930f8d9163a/lib/loady/csv_loader.rb#L23) it doesn't read a full CSV row if any of the columns contain a newline.

It would be better to use [CSV.foreach](http://ruby-doc.org/stdlib-1.9.2/libdoc/csv/rdoc/CSV.html#method-c-foreach) to loop over the rows. The CSV library reads a full row even when there are newlines in the middle of a row.

**Comment by teeparham** [comment]
Fixed by bcdd3317868e5
